services:
  api:
    build: 
      dockerfile: Dockerfile  
    env_file:
      - .env     
    ports:
      - "8000:8000"  
    volumes:
      - ./app:/app

  db:
    image: postgres:16-alpine
    env_file:
      - .env    
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data
  

  pgadmin:
    image: elestio/pgadmin:latest  
    
    env_file:
      - .env    
    ports:
      - "5050:80"  
    depends_on:
      - db

volumes:
  pgdata: